create table _user
(
    id       bigint generated by default as identity primary key,
    active   boolean     default true not null,
    name     varchar(50)              not null,
    password varchar(255),
    role     varchar(20) default 'USER'::character varying not null,
    username varchar(50)              not null
        constraint uk_username_user unique
);

create table country
(
    id   bigint generated by default as identity primary key,
    name varchar(255)
);

create table employee
(
    id         bigint generated by default as identity primary key,
    email      varchar(255),
    first_name varchar(255),
    last_name  varchar(255)
);

create table person
(
    id         bigint generated by default as identity primary key,
    name       varchar(255),
    country_id bigint
        constraint fk__person_country references country
);